server:
  port: 8080

grpc:
  client:
#    auth-service:
#      address: "static://localhost:9091"
#      negotiationType: plaintext
    booking-service:
      address: "static://localhost:9091"
      negotiationType: plaintext

jwt:
  secret: "a4f6c8d1e9b203178ab45cf9126d7f98a4f6c8d1e9b203178ab45cf9126d7f9"
  expiration: 3600000


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # cÃ³ thá»ƒ lÃ  none / validate / update / create / create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: atvncg_business  # ðŸ‘ˆ ThÃªm dÃ²ng nÃ y Ä‘á»ƒ Ä‘áº·t schema máº·c Ä‘á»‹nh