server:
  port: 8082

grpc:
  server:
    port: 9091
    in-process-name: booking-service
    security:
      enabled: false  # â¬…ï¸ Táº¯t báº£o máº­t gRPC


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # cÃ³ thá»ƒ lÃ  none / validate / update / create / create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: atvncg_business  # ğŸ‘ˆ ThÃªm dÃ²ng nÃ y Ä‘á»ƒ Ä‘áº·t schema máº·c Ä‘á»‹nh


jwt:
  secret: "a4f6c8d1e9b203178ab45cf9126d7f98a4f6c8d1e9b203178ab45cf9126d7f9"
  expiration: 3600000